using System.Text;

namespace Schipper.Io.Sqlite.Generator.Emit;

/// <summary>
/// Emits the one aggregate type that knows the whole schema: <c>Database</c> in the consuming
/// project's <c>RootNamespace</c>, so <c>MyApp</c> gets <c>MyApp.Database</c>. Override with
/// <c>[DatabaseNamespace]</c> on a row type.
///
/// A model rather than a list of SQL strings, because the question at startup is not "what should I
/// run" but "how does this database differ from what the code expects" — and only a model can answer
/// that in terms somebody can act on.
/// </summary>
internal static class SchemaClassEmitter
{
    public const string TypeName = "Database";
    public const string HintName = "Database.g.cs";

    public static string Emit(string? @namespace, IReadOnlyList<RowModel> rows)
    {
        // Sorted by table name so the hash depends on the schema and not on the order Roslyn happened
        // to hand us the files. Otherwise adding an unrelated file could report drift.
        var ordered = rows.OrderBy(r => r.Table, StringComparer.Ordinal).ToList();
        var hash = SchemaEmitter.Hash(ordered.SelectMany(static r =>
            SchemaEmitter.Statements(r).Concat(SchemaEmitter.ScaleLines(r))));

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/> Generated by Schipper.Io.Sqlite.Generator.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Schipper.Io.Sqlite;");
        sb.AppendLine("using Schipper.Io.Sqlite.Schema;");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(@namespace) && @namespace != "<global namespace>")
        {
            sb.AppendLine($"namespace {@namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// The schema, generated from the row types. There is no .sql file to keep in step because");
        sb.AppendLine("/// there is nothing to keep in step with: column type and nullability come from the same C#");
        sb.AppendLine("/// declaration the repositories are generated from.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {TypeName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Fingerprint of the whole schema. Recorded in the database and checked on start.</summary>");
        sb.AppendLine($"    public const string Hash = \"{hash}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Every table, ordered by name.</summary>");
        sb.AppendLine("    public static readonly SchemaModel Model = new(Hash, new TableModel[]");
        sb.AppendLine("    {");

        foreach (var row in ordered)
        {
            EmitTable(sb, row);
        }

        sb.AppendLine("    });");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Brings the database up to this schema and returns what it did.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// New tables, new indexes and new columns SQLite can add are applied. Anything else");
        sb.AppendLine("    /// throws <see cref=\"SqliteSchemaException\"/> naming exactly what differs.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static Task<IReadOnlyList<SchemaChange>> ApplyAsync(");
        sb.AppendLine("        SqliteDb db,");
        sb.AppendLine("        SchemaUpdate update = SchemaUpdate.Additive,");
        sb.AppendLine("        CancellationToken cancellationToken = default) =>");
        sb.AppendLine("        SchemaApplier.ApplyAsync(db, Model, update, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Reports the differences without changing anything.</summary>");
        sb.AppendLine("    public static Task<IReadOnlyList<SchemaChange>> DiffAsync(");
        sb.AppendLine("        SqliteDb db,");
        sb.AppendLine("        CancellationToken cancellationToken = default) =>");
        sb.AppendLine("        SchemaApplier.DiffAsync(db, Model, cancellationToken);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitTable(StringBuilder sb, RowModel row)
    {
        var statements = SchemaEmitter.Statements(row);
        var createTable = statements[0];
        var indexes = statements.Skip(1).ToList();

        sb.AppendLine($"        new TableModel(");
        sb.AppendLine($"            {Literal(row.Table)},");
        sb.AppendLine("            new ColumnDef[]");
        sb.AppendLine("            {");

        foreach (var column in row.Columns)
        {
            sb.AppendLine(
                $"                new({Literal(column.Name)}, {Literal(column.Map.Storage)}, " +
                $"{Bool(!column.Nullable)}, {Literal(column.Default)}, {Bool(column.IsKey)}, " +
                $"{Bool(column.Unique)}, {Bool(column.References is not null)}, " +
                $"{Literal(SchemaEmitter.ColumnDefinition(column))}, {Literal(column.RenamedFrom)}, " +
                $"{column.Map.Scale}),");
        }

        sb.AppendLine("            },");
        sb.AppendLine("            new IndexDef[]");
        sb.AppendLine("            {");

        foreach (var index in indexes)
        {
            sb.AppendLine($"                new({Literal(IndexName(index))}, {Literal(index)}),");
        }

        sb.AppendLine("            },");
        sb.AppendLine($"            {Literal(createTable)},");
        sb.AppendLine($"            {Literal(row.RenamedFrom)},");
        sb.AppendLine($"            {(row.AllowRebuild ? "true" : "false")}),");
    }

    /// <summary>Pulls the index name out of its CREATE statement, so the two cannot disagree.</summary>
    private static string IndexName(string createIndex)
    {
        const string marker = "IF NOT EXISTS ";
        var start = createIndex.IndexOf(marker, StringComparison.Ordinal) + marker.Length;

        if (start < marker.Length || start >= createIndex.Length)
        {
            return createIndex;
        }

        if (createIndex[start] == '"')
        {
            var name = new StringBuilder();
            for (var i = start + 1; i < createIndex.Length; i++)
            {
                if (createIndex[i] == '"')
                {
                    if (i + 1 < createIndex.Length && createIndex[i + 1] == '"')
                    {
                        name.Append('"');
                        i++;
                        continue;
                    }

                    return name.ToString();
                }

                name.Append(createIndex[i]);
            }

            return name.ToString();
        }

        var end = createIndex.IndexOf(' ', start);
        return end < 0 ? createIndex.Substring(start) : createIndex.Substring(start, end - start);
    }

    private static string Bool(bool value) => value ? "true" : "false";

    /// <summary>
    /// A verbatim string literal. The DDL contains newlines and single quotes; escaping only the
    /// double quote is enough and keeps the generated file readable.
    /// </summary>
    private static string Literal(string? value) =>
        value is null ? "null" : "@\"" + value.Replace("\"", "\"\"") + "\"";
}
